engines:
  rubocop:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  eslint:
    enabled: true

ratings:
  paths:
  - "lib/**"
  - "data/**"
  - "**.rb"
  - "**.js"

exclude_paths:
- "spec/**/*"
- "schemas_to_markdown.js"
